function ensure_directories(cfg)
%ENSURE_DIRECTORIES Create standard project output directories.

p = slipsolve.project.paths(cfg);
folders = [p.rawData, p.processedData, p.modelBasedSampling, p.geometry, p.greens, p.inversions, p.quickModelGrids, p.figures, ...
    p.insarSubsamplingFigures, p.faultGeometryFigures, p.triangularMeshFigures, ...
    p.quickInversionFigures, p.modelSamplingFigures, p.resampledTdeFigures, ...
    p.layeredGreensFigures, p.compositeGreensFigures, ...
    p.finalInversionFigures, p.finalFullResolutionFigures, ...
    p.lCurveFigures, p.shallowSlipDeficitFigures, p.forwardModelFigures, ...
    p.finalFullResolutionResiduals, p.lCurveDirectory, ...
    p.shallowSlipDeficitDirectory, p.forwardModelDirectory, ...
    p.layeredGreensDatabase, ...
    p.compositeGreensDirectory, p.sampledCompositeGreensDirectory, ...
    p.forwardModelGreensDirectory, p.logs];

for i = 1:numel(folders)
    if exist(folders(i), "dir") ~= 7
        mkdir(folders(i));
    end
end

end
